# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/basto/git/EmbeddedTesting/GDBManipulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/basto/git/EmbeddedTesting/GDBManipulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/basto/Downloads/clion-2018.1/bin/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(CMAKE_COMMAND) -E cmake_progress_start /home/basto/git/EmbeddedTesting/GDBManipulator/CMakeFiles /home/basto/git/EmbeddedTesting/GDBManipulator/lib/SimpleLogging/CMakeFiles/progress.marks
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f CMakeFiles/Makefile2 lib/SimpleLogging/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/basto/git/EmbeddedTesting/GDBManipulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f CMakeFiles/Makefile2 lib/SimpleLogging/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f CMakeFiles/Makefile2 lib/SimpleLogging/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f CMakeFiles/Makefile2 lib/SimpleLogging/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/rule:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f CMakeFiles/Makefile2 lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/rule
.PHONY : lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/rule

# Convenience name for target.
SimpleLoggingLib: lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/rule

.PHONY : SimpleLoggingLib

# fast build rule for target.
SimpleLoggingLib/fast:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build
.PHONY : SimpleLoggingLib/fast

src/advancedConfiguration.o: src/advancedConfiguration.cpp.o

.PHONY : src/advancedConfiguration.o

# target to build an object file
src/advancedConfiguration.cpp.o:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/advancedConfiguration.cpp.o
.PHONY : src/advancedConfiguration.cpp.o

src/advancedConfiguration.i: src/advancedConfiguration.cpp.i

.PHONY : src/advancedConfiguration.i

# target to preprocess a source file
src/advancedConfiguration.cpp.i:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/advancedConfiguration.cpp.i
.PHONY : src/advancedConfiguration.cpp.i

src/advancedConfiguration.s: src/advancedConfiguration.cpp.s

.PHONY : src/advancedConfiguration.s

# target to generate assembly for a file
src/advancedConfiguration.cpp.s:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/advancedConfiguration.cpp.s
.PHONY : src/advancedConfiguration.cpp.s

src/logging.o: src/logging.cpp.o

.PHONY : src/logging.o

# target to build an object file
src/logging.cpp.o:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/logging.cpp.o
.PHONY : src/logging.cpp.o

src/logging.i: src/logging.cpp.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.cpp.i:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/logging.cpp.i
.PHONY : src/logging.cpp.i

src/logging.s: src/logging.cpp.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.cpp.s:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(MAKE) -f lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/build.make lib/SimpleLogging/CMakeFiles/SimpleLoggingLib.dir/src/logging.cpp.s
.PHONY : src/logging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... SimpleLoggingLib"
	@echo "... src/advancedConfiguration.o"
	@echo "... src/advancedConfiguration.i"
	@echo "... src/advancedConfiguration.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/basto/git/EmbeddedTesting/GDBManipulator && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

